Add tests

diff --git a/.github/workflows/master_azurecostestimator-back.yml b/.github/workflows/master_azurecostestimator-back.yml
--- a/.github/workflows/master_azurecostestimator-back.yml
+++ b/.github/workflows/master_azurecostestimator-back.yml
@@ -57,18 +57,13 @@ jobs:
       id: show
       run: terraform show -json filetest.tfplan > ./myfiletest.json
 
-    - uses: actions/github-script@0.9.0
-      env:
-        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-      with:
-        script: |
-          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-          #### Terraform Validation 🤖${{ steps.validate.outputs.stdout }}
-          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-          
-          <details><summary>Show Plan</summary>
-          
-          \`\`\`${process.env.PLAN}\`\`\`
-          
-          </details>
+    - name: Run Pester tests (PowerShell)
+      run: |
+        Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor
+        $dire = dir
+        Write-host $dire
+        Set-PSRepository psgallery -InstallationPolicy trusted
+        Install-Module -Name Pester -RequiredVersion 5.0.4 -Confirm:$false -Force
+        Invoke-Pester -Path "./"
+        if ($Error[0].Fullyqualifiederrorid -eq 'PesterAssertionFailed') {exit 1}
+      shell: powershell
